/* Auto-generated by scripts/upload-mockups-to-supabase.mjs. */
/* Do not edit manually. */

export const MOCKUP_URLS = 
{
  "bella-3001": {
    "aqua": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/aqua-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/aqua-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/aqua-front.png"
    },
    "asphalt": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/asphalt-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/asphalt-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/asphalt-front.png"
    },
    "athletic-heather": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/athletic-heather-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/athletic-heather-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/athletic-heather-front.png"
    },
    "baby-blue": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/baby-blue-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/baby-blue-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/baby-blue-front.png"
    },
    "berry": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/berry-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/berry-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/berry-front.png"
    },
    "blanc": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/blanc-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/blanc-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/blanc-front.png"
    },
    "bordeaux": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/bordeaux-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/bordeaux-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/bordeaux-front.png"
    },
    "brown": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/brown-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/brown-front.png"
    },
    "burnt-orange": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/burnt-orange-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/burnt-orange-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/burnt-orange-front.png"
    },
    "cardinal": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/cardinal-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/cardinal-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/cardinal-front.png"
    },
    "charity-pink": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/charity-pink-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/charity-pink-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/charity-pink-front.png"
    },
    "columbia-blue": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/columbia-blue-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/columbia-blue-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/columbia-blue-front.png"
    },
    "dark-heather": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/dark-heather-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/dark-heather-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/dark-heather-front.png"
    },
    "forest": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/forest-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/forest-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/forest-front.png"
    },
    "gold": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/gold-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/gold-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/gold-front.png"
    },
    "heather-navy": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/heather-navy-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/heather-navy-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/heather-navy-front.png"
    },
    "kelly": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/kelly-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/kelly-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/kelly-front.png"
    },
    "leaf": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/leaf-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/leaf-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/leaf-front.png"
    },
    "lilac": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/lilac-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/lilac-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/lilac-front.png"
    },
    "marine": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/marine-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/marine-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/marine-front.png"
    },
    "mauve": {
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/mauve-front.png"
    },
    "mint": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/mint-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/mint-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/mint-front.png"
    },
    "mustard": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/mustard-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/mustard-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/mustard-front.png"
    },
    "natural": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/natural-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/natural-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/natural-front.png"
    },
    "noir": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/noir-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/noir-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/noir-front.png"
    },
    "olive": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/olive-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/olive-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/olive-front.png"
    },
    "orange": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/orange-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/orange-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/orange-front.png"
    },
    "rouge": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/rouge-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/rouge-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/rouge-front.png"
    },
    "sand": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/sand-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/sand-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/sand-front.png"
    },
    "soft-cream": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/soft-cream-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/soft-cream-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/soft-cream-front.png"
    },
    "steel-blue": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/steel-blue-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/steel-blue-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/steel-blue-front.png"
    },
    "teal": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/teal-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/teal-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/teal-front.png"
    },
    "true-royal": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/true-royal-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/true-royal-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/true-royal-front.png"
    },
    "vert-militaire": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/vert-militaire-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/vert-militaire-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/vert-militaire-front.png"
    },
    "violet": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/violet-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/violet-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/violet-front.png"
    },
    "yellow": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/yellow-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/yellow-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/bella-3001/yellow-front.png"
    }
  },
  "gildan-18000": {
    "blanc": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/blanc-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/blanc-front.png"
    },
    "gris": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/gris-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/gris-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/gris-front.png"
    },
    "gris-sport": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/gris-sport-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/gris-sport-front.png"
    },
    "marine": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/marine-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/marine-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/marine-front.png"
    },
    "noir": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/noir-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/noir-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18000/noir-front.png"
    }
  },
  "gildan-18500": {
    "blanc": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/blanc-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/blanc-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/blanc-front.png"
    },
    "bleu-carolina": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bleu-carolina-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bleu-carolina-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bleu-carolina-front.png"
    },
    "bleu-clair": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bleu-clair-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bleu-clair-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bleu-clair-front.png"
    },
    "bordeaux": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bordeaux-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bordeaux-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/bordeaux-front.png"
    },
    "charcoal": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/charcoal-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/charcoal-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/charcoal-front.png"
    },
    "chocolat": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/chocolat-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/chocolat-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/chocolat-front.png"
    },
    "dark-heather": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/dark-heather-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/dark-heather-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/dark-heather-front.png"
    },
    "gris": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/gris-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/gris-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/gris-front.png"
    },
    "gris-graphite": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/gris-graphite-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/gris-graphite-front.png"
    },
    "gris-sport": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/gris-sport-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/gris-sport-front.png"
    },
    "heliconia": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/heliconia-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/heliconia-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/heliconia-front.png"
    },
    "indigo": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/indigo-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/indigo-front.png"
    },
    "marine": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/marine-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/marine-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/marine-front.png"
    },
    "noir": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/noir-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/noir-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/noir-front.png"
    },
    "or": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/or-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/or-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/or-front.png"
    },
    "orange": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/orange-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/orange-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/orange-front.png"
    },
    "rose-clair": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/rose-clair-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/rose-clair-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/rose-clair-front.png"
    },
    "rouge": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/rouge-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/rouge-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/rouge-front.png"
    },
    "royal": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/royal-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/royal-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/royal-front.png"
    },
    "sable": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/sable-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/sable-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/sable-front.png"
    },
    "vert-foret": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-foret-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-foret-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-foret-front.png"
    },
    "vert-irlandais": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-irlandais-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-irlandais-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-irlandais-front.png"
    },
    "vert-militaire": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-militaire-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-militaire-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/vert-militaire-front.png"
    },
    "violet": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/violet-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/violet-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-18500/violet-front.png"
    }
  },
  "gildan-5000": {
    "blanc": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/blanc-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/blanc-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/blanc-front.png"
    },
    "default": {
      "bordeaux-back-v2": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/bordeaux-back-v2.png",
      "bordeaux-front-v2": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/bordeaux-front-v2.png"
    },
    "bordeaux": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/bordeaux-back.png",
      "detail-v2": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/bordeaux-detail-v2.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/bordeaux-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/bordeaux-front.png"
    },
    "gris": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/gris-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/gris-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/gris-front.png"
    },
    "gris-sport": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/gris-sport-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/gris-sport-front.png"
    },
    "marine": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/marine-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/marine-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/marine-front.png"
    },
    "noir": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/noir-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/noir-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/noir-front.png"
    },
    "rouge": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/rouge-back.png",
      "detail": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/rouge-detail.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/gildan-5000/rouge-front.png"
    }
  },
  "hm/textile/gildan-18000/noir-old": {
    "default": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/hm/textile/gildan-18000/noir-old/back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/hm/textile/gildan-18000/noir-old/front.png"
    }
  },
  "print/affiche": {
    "default": {
      "affiche-premium": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/print/affiche/affiche-premium.png"
    }
  },
  "print/business-card": {
    "default": {
      "carte-visite-premium": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/print/business-card/carte-visite-premium.png",
      "carte-visite-render": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/print/business-card/carte-visite-render.png"
    }
  },
  "print/canvas": {
    "default": {
      "canvas-premium": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/print/canvas/canvas-premium.png"
    }
  },
  "print/flyer": {
    "default": {
      "flyer-premium": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/print/flyer/flyer-premium.png"
    }
  },
  "tshirt/backup": {
    "blanc": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/blanc-back.png"
    },
    "bleu": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/bleu-back.png"
    },
    "bordeaux": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/bordeaux-back.png",
      "front": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/bordeaux-front.png"
    },
    "gris": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/gris-back.png"
    },
    "marine": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/marine-back.png"
    },
    "noir": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/noir-back.png"
    },
    "rouge": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/rouge-back.png"
    },
    "vert": {
      "back": "https://kbeeedbfkalovtusaden.supabase.co/storage/v1/object/public/mockups/tshirt/backup/vert-back.png"
    }
  }
} as const;

export type MockupUrls = typeof MOCKUP_URLS;
