/**
 * lib/hermes/mock-data.ts — Données mockées Hermès OS V1.
 *
 * Toutes les listes sont exportées en lecture seule. Quand Supabase sera prêt,
 * on remplacera ces exports par des fonctions async qui requêtent les tables.
 * Les composants de pages n'ont qu'à muter leur import.
 */

import type {
  HermesAgent,
  HermesMemoryEntry,
  HermesProject,
  HermesPrompt,
  HermesReport,
  HermesSalesProspect,
  HermesTask,
} from "./types";

// ── Agents IA ──────────────────────────────────────────────────────────────

export const MOCK_AGENTS: HermesAgent[] = [
  {
    id: "claude-code",
    name: "Claude Code",
    shortName: "Code",
    role: "Code, debug, Git, Vercel, architecture et corrections de bugs.",
    bestFor: ["Corriger une page", "Préparer une branche", "Analyser une erreur build"],
    accent: "#9ed7e8",
    category: "claude-code",
  },
  {
    id: "claude-navigation",
    name: "Claude Navigation",
    shortName: "Navigation",
    role: "Tester dans le navigateur, cliquer, vérifier Supabase, Vercel, Railway, Discord et pages web.",
    bestFor: ["Tester un parcours", "Vérifier une interface", "Contrôler un déploiement"],
    accent: "#86efac",
    category: "claude-navigation",
  },
  {
    id: "chatgpt-strategist",
    name: "ChatGPT Stratège",
    shortName: "Stratège",
    role: "Analyse, rédaction, stratégie, prompts, décision et structuration.",
    bestFor: ["Clarifier une demande", "Rédiger un brief", "Décider une priorité"],
    accent: "#fde68a",
    category: "chatgpt",
  },
  {
    id: "hermes-discord",
    name: "Hermès Bot Discord",
    shortName: "Discord",
    role: "Commandes rapides, rapports courts, notifications et suivi depuis Discord.",
    bestFor: ["Recevoir un rapport", "Créer une alerte", "Suivre une mission courte"],
    accent: "#c4b5fd",
    category: "discord",
  },
  {
    id: "email-agent",
    name: "Agent Email",
    shortName: "Email",
    role: "Préparer emails clients, relances, réponses professionnelles et administratif.",
    bestFor: ["Répondre à un client", "Préparer une relance", "Rédiger un email propre"],
    accent: "#f9c9dd",
    category: "email",
  },
  {
    id: "quote-agent",
    name: "Agent Devis",
    shortName: "Devis",
    role: "Transformer demandes clients en fiches devis Pennylane.",
    bestFor: ["Structurer une demande", "Lister les infos manquantes", "Préparer un devis"],
    accent: "#fbbf24",
    category: "devis",
  },
  {
    id: "design-agent",
    name: "Agent Design / DA",
    shortName: "Design",
    role: "Analyser interface, mockups, visuels, cohérence graphique et direction artistique.",
    bestFor: ["Auditer une page", "Comparer des mockups", "Améliorer une interface"],
    accent: "#f0abfc",
    category: "design",
  },
  {
    id: "admin-finance-agent",
    name: "Agent Admin / Finance",
    shortName: "Admin",
    role: "Banques, aides, factures, documents et suivi administratif.",
    bestFor: ["Préparer un dossier", "Suivre une facture", "Clarifier une aide"],
    accent: "#93c5fd",
    category: "admin",
  },
  {
    id: "sales-agent",
    name: "Agent Vente Strasbourg",
    shortName: "Vente",
    role: "Prospection B2B locale, classement des prospects, scripts d'appel, emails et suivi commercial.",
    bestFor: ["Trouver des prospects Strasbourg", "Préparer appels et emails", "Qualifier un besoin textile ou print"],
    accent: "#86efac",
    category: "prospection",
  },
  {
    id: "personal-agent",
    name: "Agent Personnel",
    shortName: "Personnel",
    role: "Organisation personnelle, rappels et tâches hors agence.",
    bestFor: ["Planifier la semaine", "Créer un rappel", "Trier les priorités perso"],
    accent: "#d9f99d",
    category: "personnel",
  },
];

// ── Projets ────────────────────────────────────────────────────────────────

export const MOCK_PROJECTS: HermesProject[] = [
  {
    id:          "proj-site",
    name:        "Site HM Global",
    category:    "site-web",
    status:      "active",
    description: "E-commerce textile + impression. Tunnel devis, studio personnalisation, fiches produits.",
    objective:   "Faire vendre et demander des devis sans friction.",
    updatedAt:   "2026-05-19T08:00:00Z",
  },
  {
    id:          "proj-impression",
    name:        "Page /impression",
    category:    "impression",
    status:      "active",
    description: "Refonte commerciale B2B (mockups Pixart-inspired). Lot 1 bis en validation.",
    objective:   "Rendre l'offre print lisible et crédible pour les clients pro.",
    updatedAt:   "2026-05-19T11:30:00Z",
  },
  {
    id:          "proj-textile",
    name:        "Production textile",
    category:    "textile",
    status:      "active",
    description: "Suivi commandes textile, BAT, broderie / DTF. Agent Jean-Yves prévu.",
    objective:   "Centraliser production, BAT et fournisseurs textile.",
    updatedAt:   "2026-05-18T17:00:00Z",
  },
  {
    id:          "proj-hermes",
    name:        "Hermès OS",
    category:    "hermes-os",
    status:      "active",
    description: "Cockpit IA interne pour piloter rapports, missions, tâches, mémoire et agents.",
    objective:   "Donner à Kaan une interface claire pour piloter les agents IA.",
    updatedAt:   "2026-05-20T09:00:00Z",
  },
  {
    id:          "proj-vente",
    name:        "Vente & prospection Strasbourg",
    category:    "vente",
    status:      "active",
    description: "Pipeline commercial local : Google Maps, sites web, réseaux sociaux, appels, emails et relances.",
    objective:   "Créer un flux régulier de prospects B2B qualifiés pour HM Global.",
    updatedAt:   "2026-05-26T09:00:00Z",
  },
  {
    id:          "proj-discord",
    name:        "Discord Bot",
    category:    "discord",
    status:      "active",
    description: "Commandes rapides, rapports courts et notifications connectées à Hermès OS.",
    objective:   "Faire remonter les rapports courts dans Rapports agents.",
    updatedAt:   "2026-05-19T10:30:00Z",
  },
  {
    id:          "proj-erasmus",
    name:        "Erasmus KA210",
    category:    "erasmus",
    status:      "active",
    description: "Projet Erasmus KA210. Suivi pédagogique + budget + rapports.",
    objective:   "Garder les livrables Erasmus à jour sans perdre les dates.",
    updatedAt:   "2026-05-17T12:00:00Z",
  },
  {
    id:          "proj-admin",
    name:        "Admin & finance",
    category:    "finance",
    status:      "active",
    description: "CGV, mentions légales, RGPD, banques, aides et factures fournisseurs.",
    objective:   "Suivre les obligations et documents sans surcharge mentale.",
    updatedAt:   "2026-05-10T14:20:00Z",
  },
  {
    id:          "proj-personnel",
    name:        "Personnel",
    category:    "personnel",
    status:      "active",
    description: "Organisation personnelle, rappels, rythme de travail et tâches hors agence.",
    objective:   "Séparer le personnel de l'agence tout en gardant une vue claire.",
    updatedAt:   "2026-05-12T10:00:00Z",
  },
];

// ── Rapports ───────────────────────────────────────────────────────────────

export const MOCK_REPORTS: HermesReport[] = [
  {
    id:        "rep-001",
    title:     "Lot 1 bis — 10 mockups print hybride A+B",
    source:    "claude-code",
    status:    "new",
    createdAt: "2026-05-19T11:45:00Z",
    summary:   "5 catégories × 2 variantes générées sur ChatGPT. Reco par image. En attente de validation pour téléchargement et intégration.",
    body:      "Carte Premium V2, Carte Standard V2, Affiche V1, Flyers A5 V1, Brochures V2 recommandées. 70% B2B plateforme print + 30% premium agence HM. Aucun gradient pleine page, accents HM seulement.",
    agentId:   "claude-code",
    projectId: "proj-impression",
    channel:   "agent",
    priority:  "P1",
    reportType: "audit",
    tags:      ["print", "mockups", "validation"],
  },
  {
    id:        "rep-002",
    title:     "Hermes Report Exporter — fonctionnalité livrée",
    source:    "claude-code",
    status:    "validated",
    createdAt: "2026-05-19T10:30:00Z",
    summary:   "/hermes_copy_last et /hermes_copy_message implémentés. 3 fichiers nouveaux, 2 edits, type-check OK.",
    body:      "Ajout slash commands pour exporter les rapports Hermès en bloc Markdown ou fichier .txt. Lecture REST Discord. Pas de refactor. Reste à enregistrer les commandes via npm run discord:register.",
    agentId:   "claude-code",
    projectId: "proj-discord",
    channel:   "agent",
    priority:  "P2",
    reportType: "execution",
    githubBranch: "mission/hermes-bot-discord-v0",
    tags:      ["bot", "discord", "feature"],
  },
  {
    id:        "rep-003",
    title:     "Audit catalogue textile — visibilité produits",
    source:    "claude-code",
    status:    "read",
    createdAt: "2026-05-19T09:15:00Z",
    summary:   "45 produits, 38 visibles, 7 invisibles. 4 sacs avec colors[] vs TOPTEX_IMGS désalignés.",
    body:      "Liste des SKU à corriger : ki0262, ki0252, ki0275, ki0274. Options A/B/C présentées, attente choix.",
    agentId:   "claude-code",
    projectId: "proj-textile",
    channel:   "agent",
    priority:  "P2",
    reportType: "audit",
    tags:      ["catalogue", "audit"],
  },
  {
    id:        "rep-004",
    title:     "Analyse stratégique Pixart vs HM /impression",
    source:    "claude-code",
    status:    "validated",
    createdAt: "2026-05-19T11:00:00Z",
    summary:   "8 sections : ce que Pixart fait bien, ce que HM fait moins bien, restructuration images, mockups à créer, stratégie prompts.",
    body:      "Direction validée 70 B2B / 30 premium agence. Lot 1 bis relancé avec grammaire commerciale. 9 SKU vendables prévus phase 2.",
    agentId:   "design-agent",
    projectId: "proj-impression",
    channel:   "manual",
    priority:  "P2",
    reportType: "decision",
    tags:      ["strategie", "ux", "print"],
  },
  {
    id:        "rep-005",
    title:     "Caption Instagram — post mockup carte tenue",
    source:    "chatgpt",
    status:    "to_review",
    createdAt: "2026-05-18T16:00:00Z",
    summary:   "Caption FR 80 caractères + hashtags. Ton chaleureux mais pro. À relire avant publication.",
    body:      "Caption brouillon : 'La carte qui se tient toute seule. Papier 350g/m², finition mate, accent rose HM Global. Devis offert.' #cartedevisite #imprimerie #alsace",
    agentId:   "chatgpt-strategist",
    projectId: "proj-impression",
    channel:   "agent",
    priority:  "P3",
    reportType: "brief",
    tags:      ["caption", "social"],
  },
  {
    id:        "rep-006",
    title:     "Brouillon CGV section livraison",
    source:    "manuel",
    status:    "rejected",
    createdAt: "2026-05-15T14:00:00Z",
    summary:   "Section 7.3 trop floue sur délai textile vs print. Avocat a demandé refonte.",
    body:      "Texte à revoir avec délais explicites par catégorie. À renvoyer en V2.",
    agentId:   "admin-finance-agent",
    projectId: "proj-admin",
    channel:   "manual",
    priority:  "P2",
    reportType: "note",
    tags:      ["legal", "cgv"],
  },
  {
    id:        "rep-007",
    title:     "Retour Discord — notification rapport court",
    source:    "discord",
    status:    "new",
    createdAt: "2026-05-20T08:30:00Z",
    summary:   "Le bot peut pousser un résumé court vers Hermès OS. À classer dans Rapports agents puis transformer en tâche si utile.",
    body:      "Message Discord reçu : mission test navigation prête. Attente validation Kaan avant exécution.",
    agentId:   "hermes-discord",
    projectId: "proj-discord",
    channel:   "discord",
    priority:  "P2",
    reportType: "note",
    discordMessageId: "mock-discord-001",
    tags:      ["discord", "rapport-court"],
  },
];

// ── Tâches ─────────────────────────────────────────────────────────────────

export const MOCK_TASKS: HermesTask[] = [
  {
    id:        "task-001",
    title:     "Valider variantes Lot 1 bis (5 visuels)",
    status:    "todo",
    createdAt: "2026-05-19T11:50:00Z",
    dueAt:     "2026-05-20T00:00:00Z",
    projectId: "proj-impression",
    reportId:  "rep-001",
    agentId:   "design-agent",
    priority:  "P1",
    nextAction: "Choisir les variantes à intégrer.",
  },
  {
    id:        "task-002",
    title:     "Enregistrer slash commands /hermes_copy_*",
    status:    "todo",
    createdAt: "2026-05-19T10:35:00Z",
    projectId: "proj-discord",
    reportId:  "rep-002",
    agentId:   "claude-code",
    priority:  "P1",
    nextAction: "Lancer l'enregistrement côté bot.",
    notes:     "Lancer : cd hm-hermes-bot && npm run discord:register",
  },
  {
    id:        "task-003",
    title:     "Choisir option correction sacs (A/B/C)",
    status:    "todo",
    createdAt: "2026-05-19T09:20:00Z",
    projectId: "proj-textile",
    reportId:  "rep-003",
    agentId:   "chatgpt-strategist",
    priority:  "P2",
    nextAction: "Choisir A, B ou C puis préparer mission code.",
  },
  {
    id:        "task-004",
    title:     "Intégrer mockups validés (page /impression)",
    status:    "doing",
    createdAt: "2026-05-19T12:00:00Z",
    projectId: "proj-impression",
    agentId:   "claude-code",
    priority:  "P1",
    nextAction: "Attendre validation des visuels.",
    notes:     "Sera lancé dès que les 5 variantes Lot 1 bis sont validées.",
  },
  {
    id:        "task-005",
    title:     "Refonte CGV section 7.3 (livraison)",
    status:    "waiting_agent",
    createdAt: "2026-05-16T11:00:00Z",
    projectId: "proj-admin",
    reportId:  "rep-006",
    agentId:   "admin-finance-agent",
    priority:  "P2",
    nextAction: "Attendre retour texte V2.",
  },
  {
    id:        "task-006",
    title:     "Memoire agent-memory restructurée (10 fichiers)",
    status:    "done",
    createdAt: "2026-05-18T08:00:00Z",
    projectId: "proj-hermes",
    agentId:   "claude-code",
    priority:  "P2",
    nextAction: "Archiver comme référence.",
  },
  {
    id:        "task-007",
    title:     "Fix HMProductVisual mode supplier (fond fafafa)",
    status:    "done",
    createdAt: "2026-05-17T09:00:00Z",
    projectId: "proj-site",
    agentId:   "claude-code",
    priority:  "P2",
    nextAction: "Aucune.",
  },
  {
    id:        "task-009",
    title:     "Qualifier 30 entreprises Strasbourg pour textile + print",
    status:    "todo",
    createdAt: "2026-05-26T09:15:00Z",
    projectId: "proj-vente",
    agentId:   "sales-agent",
    priority:  "P1",
    nextAction: "Chercher par secteur Google Maps puis valider téléphone, site et réseaux.",
    notes:     "Cibler d'abord restauration, BTP, sport, beauté, événementiel et immobilier.",
  },
  {
    id:        "task-010",
    title:     "Préparer script d'appel court pour offres HM Global",
    status:    "todo",
    createdAt: "2026-05-26T09:20:00Z",
    projectId: "proj-vente",
    agentId:   "sales-agent",
    priority:  "P1",
    nextAction: "Créer une accroche 20 secondes + question de qualification.",
  },
  {
    id:        "task-008",
    title:     "Hermes Gateway Railway deploy",
    status:    "done",
    createdAt: "2026-05-18T17:30:00Z",
    projectId: "proj-discord",
    agentId:   "claude-navigation",
    priority:  "P1",
    nextAction: "Contrôler le prochain déploiement.",
  },
];

// ── Prospection vente ─────────────────────────────────────────────────────

export const MOCK_SALES_PROSPECTS: HermesSalesProspect[] = [
  {
    id: "sale-001",
    companyName: "Restaurants & traiteurs centre Strasbourg",
    sector: "Restauration",
    city: "Strasbourg",
    status: "to_call",
    priority: "hot",
    score: 91,
    needs: ["textile-staff", "print", "événementiel"],
    signals: [
      "Équipes visibles en salle ou livraison",
      "Besoin fréquent de polos, tabliers, menus, flyers",
      "Décision souvent locale et rapide",
    ],
    recommendedOffer: "Pack ouverture / saison : tabliers brodés, polos staff, flyers et cartes de fidélité.",
    nextAction: "Appeler le gérant, demander qui gère les tenues et supports print.",
    channels: ["phone", "website", "instagram", "google"],
    source: "manuel",
    notes: "Premier lot à générer via Google Places : restaurant Strasbourg, traiteur Strasbourg, food truck Strasbourg.",
  },
  {
    id: "sale-002",
    companyName: "Garages, detailing et lavage auto Strasbourg",
    sector: "Automobile",
    city: "Strasbourg",
    status: "qualified",
    priority: "hot",
    score: 88,
    needs: ["textile-staff", "signalétique", "print"],
    signals: [
      "Personnel atelier avec vêtements de travail",
      "Fort besoin d'image locale et de visibilité",
      "Photos Instagram souvent exploitables pour personnalisation",
    ],
    recommendedOffer: "Vestes, sweats ou polos brodés + cartes de visite + stickers véhicule.",
    nextAction: "Lister 15 garages avec téléphone pro et Instagram avant appel.",
    channels: ["phone", "website", "instagram", "google"],
    source: "manuel",
  },
  {
    id: "sale-003",
    companyName: "Clubs sportifs et associations Strasbourg Eurométropole",
    sector: "Sport & associations",
    city: "Strasbourg",
    status: "email_ready",
    priority: "hot",
    score: 86,
    needs: ["textile-staff", "événementiel", "cadeaux-pro"],
    signals: [
      "Besoin récurrent de sweats, t-shirts, polos et sacs",
      "Commandes groupées possibles",
      "Saisonnalité forte avant rentrée et tournois",
    ],
    recommendedOffer: "Pack club : sweat + t-shirt + sac, devis par quantité et tailles.",
    nextAction: "Préparer un email court avec exemple de pack club et demande de tailles.",
    channels: ["email", "website", "instagram", "facebook", "google"],
    source: "manuel",
  },
  {
    id: "sale-004",
    companyName: "Salons de coiffure, barber shops et instituts",
    sector: "Beauté",
    city: "Strasbourg",
    status: "to_call",
    priority: "warm",
    score: 78,
    needs: ["textile-staff", "print", "rebranding"],
    signals: [
      "Image de marque visible en boutique",
      "Instagram souvent actif",
      "Besoin possible de cartes de rendez-vous, flyers, tabliers",
    ],
    recommendedOffer: "Tabliers personnalisés + cartes de rendez-vous + flyers offre découverte.",
    nextAction: "Vérifier Instagram et appeler sur horaires creux.",
    channels: ["phone", "instagram", "website", "google"],
    source: "manuel",
  },
  {
    id: "sale-005",
    companyName: "Entreprises BTP, artisans et paysagistes",
    sector: "BTP & artisans",
    city: "Strasbourg",
    status: "qualified",
    priority: "hot",
    score: 84,
    needs: ["textile-staff", "signalétique", "print"],
    signals: [
      "Tenues terrain utiles pour crédibilité chantier",
      "Véhicules et panneaux de chantier à rendre cohérents",
      "Décideurs souvent joignables par téléphone",
    ],
    recommendedOffer: "Pack chantier : softshell ou sweat brodé, t-shirts, cartes et panneaux chantier.",
    nextAction: "Créer une liste de 20 artisans avec numéro fixe/mobile pro.",
    channels: ["phone", "website", "google"],
    source: "manuel",
  },
  {
    id: "sale-006",
    companyName: "Agences immobilières indépendantes",
    sector: "Immobilier",
    city: "Strasbourg",
    status: "new",
    priority: "warm",
    score: 72,
    needs: ["print", "signalétique", "cadeaux-pro"],
    signals: [
      "Besoin de cartes, flyers, panneaux, pochettes clients",
      "Image premium importante",
      "Décideur identifiable sur le site",
    ],
    recommendedOffer: "Cartes premium, flyers estimation, panneaux à vendre et cadeaux clients.",
    nextAction: "Identifier les agences indépendantes avec site ancien ou supports faibles.",
    channels: ["phone", "email", "website", "linkedin", "google"],
    source: "manuel",
  },
];

// ── Mémoire ────────────────────────────────────────────────────────────────

export const MOCK_MEMORY: HermesMemoryEntry[] = [
  {
    id:        "mem-001",
    section:   "regles-design",
    title:     "Palette HM Global officielle (2026)",
    body:      "Cyan #54B6D2, Violet profond #3B235A, Magenta #C13C8A. Crème #F7F3EA pour fonds neutres. Toujours utiliser ces tokens via var(--hm-cyan), var(--hm-violet), var(--hm-magenta).",
    updatedAt: "2026-05-10T12:00:00Z",
  },
  {
    id:        "mem-002",
    section:   "regles-design",
    title:     "Mockups print — accent only, jamais plein gradient",
    body:      "Les couleurs HM apparaissent en accents 10-20% surface max : carré monogramme, bandeau cut, accent square. Jamais en gradient pleine carte/page. 70% papier mat blanc visible.",
    updatedAt: "2026-05-19T11:30:00Z",
  },
  {
    id:        "mem-003",
    section:   "regles-techniques",
    title:     "MockupViewer B3.2-A2 — zones figées",
    body:      "Fabric.js v6, zones cœur [0.60,0.25,0.14,0.14] et dos [0.26,0.13,0.48,0.29] calibrées en production. Ne jamais modifier sans audit visuel complet.",
    updatedAt: "2026-04-15T10:00:00Z",
  },
  {
    id:        "mem-004",
    section:   "regles-techniques",
    title:     "Variables Supabase Vercel — ne pas toucher",
    body:      "NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY déjà configurées en prod. Toute modification casse auth et upload.",
    updatedAt: "2026-04-20T09:00:00Z",
  },
  {
    id:        "mem-005",
    section:   "process",
    title:     "Workflow BAT — validation client obligatoire",
    body:      "Avant production : 1) Upload logo, 2) Studio personnalisation, 3) BAT preview, 4) Validation client par email, 5) Lancement production. Aucune impression sans BAT signé.",
    updatedAt: "2026-05-01T14:00:00Z",
  },
  {
    id:        "mem-006",
    section:   "decisions",
    title:     "2026-05-19 — Hermès OS choisi comme dashboard principal",
    body:      "Discord garde les alertes courtes + validations rapides. Toute la lecture, classement, copie de rapports passe par /hermes (Next.js + Supabase). Démarrage en V1 avec mock data.",
    updatedAt: "2026-05-19T12:00:00Z",
  },
  {
    id:        "mem-007",
    section:   "decisions",
    title:     "2026-05-19 — Direction print /impression : hybride 70 B2B / 30 premium",
    body:      "Plus de gradient pleine page. Mockups doivent montrer un placeholder de mise en page commercial. Les couleurs HM apparaissent en accents ponctuels seulement.",
    updatedAt: "2026-05-19T11:30:00Z",
  },
  {
    id:        "mem-008",
    section:   "prompts",
    title:     "Meta-prompt mockup print HM Global",
    body:      "Voir docs/prompts/print-mockups-prompts.md pour la grammaire commune : palette, lumière 45° haut-gauche, no hands, no text, no logos, ratio 4:3, papier visible 70%.",
    updatedAt: "2026-05-18T20:00:00Z",
  },
];

// ── Prompts ────────────────────────────────────────────────────────────────

export const MOCK_PROMPTS: HermesPrompt[] = [
  {
    id:        "prm-001",
    title:     "Mockup carte de visite premium (B2B)",
    category:  "chatgpt",
    body:      "Premium product photograph of a single printed business card standing upright leaning against a closed black leather agenda book on a clean warm off-white wooden desk surface. The card shows a REALISTIC layout: small cyan monogram block top-left, 4 horizontal thin grey placeholder lines, small magenta accent square bottom-right. 75% white paper visible. Soft natural light upper-left 45°. Ratio 4:3. No hands, no text, no logos.",
    updatedAt: "2026-05-19T11:45:00Z",
    agentId:   "design-agent",
    usage:     "Générer un visuel produit premium.",
    tag:       "Mockup",
    notes:     "Variante : ajouter agenda cuir noir = signal B2B pro.",
  },
  {
    id:        "prm-002",
    title:     "Stack cartes de visite top-down avec ficelle jute",
    category:  "chatgpt",
    body:      "Top-down flat lay photograph (90° overhead) of 25 business cards stacked, wrapped with natural raw jute twine and a small knot upper-right. Top card layout: cyan monogram top-left, grey placeholder lines, magenta accent square bottom-right. Side edge shows ~25 paper layers (8mm tall). Clean warm off-white background. Soft natural light upper-left 40°. Ratio 4:3. No hands, no plants.",
    updatedAt: "2026-05-19T11:50:00Z",
    agentId:   "design-agent",
    usage:     "Créer une variante visuelle plus artisanale.",
    tag:       "Mockup",
  },
  {
    id:        "prm-003",
    title:     "Mission Claude Code — squelette type",
    category:  "claude-code",
    body:      "Mission [titre court]. Contexte : [paragraphe]. Périmètre : [paths]. Interdits : [paths protégés]. Méthode : étape 1, 2, 3. Tests : npm run type-check + smoke test. Livrable : diff sur branche [nom], pas de commit avant validation.",
    updatedAt: "2026-04-30T09:00:00Z",
    agentId:   "claude-code",
    usage:     "Préparer une mission code claire et bornée.",
    tag:       "Mission",
    notes:     "Adapter le périmètre selon repo : hm-global, hm-hermes-bot, hm-hermes-gateway.",
  },
  {
    id:        "prm-004",
    title:     "Caption Instagram — post produit",
    category:  "chatgpt",
    body:      "[Phrase d'accroche 8-10 mots]. [Description produit 1 phrase]. [Bénéfice client]. [CTA discret]. #hashtag1 #hashtag2 #hashtag3 #imprimerie #alsace",
    updatedAt: "2026-05-12T10:00:00Z",
    agentId:   "chatgpt-strategist",
    usage:     "Préparer une publication courte.",
    tag:       "Social",
  },
  {
    id:        "prm-005",
    title:     "Message prospection LinkedIn — premier contact",
    category:  "email",
    body:      "Bonjour [Prénom], je suis [Nom], agence HM Global à Souffelweyersheim. J'accompagne les entreprises [secteur] sur leur identité visuelle textile et print. Je vous écris parce que [raison spécifique]. Auriez-vous 15 min pour échanger sur [sujet] ? Bonne journée.",
    updatedAt: "2026-04-22T16:00:00Z",
    agentId:   "email-agent",
    usage:     "Préparer un premier contact professionnel.",
    tag:       "Prospection",
  },
  {
    id:        "prm-006",
    title:     "Brief Erasmus — rapport mensuel",
    category:  "erasmus",
    body:      "Mois de [mois]. Activités réalisées : [liste]. Indicateurs : [chiffres]. Budget engagé : [montant € / montant total €]. Points d'attention : [risques]. Prochaines étapes : [actions semaine suivante].",
    updatedAt: "2026-05-01T11:00:00Z",
    agentId:   "admin-finance-agent",
    usage:     "Structurer un rapport Erasmus mensuel.",
    tag:       "Rapport",
  },
  {
    id:        "prm-007",
    title:     "Devis textile express — broderie 50 unités",
    category:  "devis",
    body:      "Article : [référence]. Coloris : [liste]. Tailles : [répartition]. Quantité : [n]. Zone marquage : [cœur/dos/coeur-dos]. Technique : broderie. Surcoût marquage : [€/pièce]. Délai : [jours ouvrés]. Total HT : [montant €]. Validité : 30 jours.",
    updatedAt: "2026-05-08T14:00:00Z",
    agentId:   "quote-agent",
    usage:     "Transformer une demande textile en base de devis.",
    tag:       "Devis",
  },
  {
    id:        "prm-008",
    title:     "Hermès Bot — /hermes mission [audit|exec|doc]",
    category:  "discord",
    body:      "/hermes mission titre:[court] type:[audit|exec|doc] priority:[P1|P2|P3] context:[1 phrase pourquoi cette mission existe]",
    updatedAt: "2026-05-19T10:30:00Z",
    agentId:   "hermes-discord",
    usage:     "Créer une mission rapide depuis Discord.",
    tag:       "Commande",
    notes:     "Le bot renvoie un bloc mission structuré, copiable dans docs/hermes/missions/.",
  },
  {
    id:        "prm-009",
    title:     "Test navigateur — page à vérifier",
    category:  "claude-navigation",
    body:      "Objectif : tester [URL/page]. Parcours : ouvrir la page, vérifier les textes visibles, cliquer sur [éléments], contrôler responsive mobile, noter bugs bloquants et captures utiles. Livrable : rapport court avec OK / à corriger / prochaines actions.",
    updatedAt: "2026-05-20T08:00:00Z",
    agentId:   "claude-navigation",
    usage:     "Préparer un contrôle navigateur.",
    tag:       "QA",
  },
  {
    id:        "prm-010",
    title:     "Organisation personnelle — point rapide",
    category:  "personnel",
    body:      "Contexte personnel : [situation]. Objectif : clarifier les priorités des 48 prochaines heures. Contraintes : [temps/énergie/déplacements]. Sortie attendue : 3 priorités max, tâches simples, rappels utiles, aucune surcharge.",
    updatedAt: "2026-05-20T08:10:00Z",
    agentId:   "personal-agent",
    usage:     "Clarifier une journée ou une semaine.",
    tag:       "Perso",
  },
];
